# Generated by Buildr 1.4.4, change to your liking
# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "chelsea"
COPYRIGHT = ""

# Tell buildr we want to compile Scala
require 'buildr/scala'

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2/"
repositories.remote << "http://scala-tools.org/repo-releases/"

desc "A HandlerSocket client written in Scala"
define "chelsea" do
  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  compile.with "net.lag:configgy:jar:2.0.0"
end
